/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsTooltipRouteImport } from './routes/docs/tooltip'
import { Route as DocsToastRouteImport } from './routes/docs/toast'
import { Route as DocsTextareaRouteImport } from './routes/docs/textarea'
import { Route as DocsTabsRouteImport } from './routes/docs/tabs'
import { Route as DocsTableRouteImport } from './routes/docs/table'
import { Route as DocsSwitchRouteImport } from './routes/docs/switch'
import { Route as DocsSpinnerRouteImport } from './routes/docs/spinner'
import { Route as DocsSliderRouteImport } from './routes/docs/slider'
import { Route as DocsSelectRouteImport } from './routes/docs/select'
import { Route as DocsRadioRouteImport } from './routes/docs/radio'
import { Route as DocsProgressRouteImport } from './routes/docs/progress'
import { Route as DocsPhilosophyRouteImport } from './routes/docs/philosophy'
import { Route as DocsNavMenuRouteImport } from './routes/docs/nav-menu'
import { Route as DocsLabelRouteImport } from './routes/docs/label'
import { Route as DocsInputRouteImport } from './routes/docs/input'
import { Route as DocsHidamariTextRouteImport } from './routes/docs/hidamari-text'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsDropdownMenuRouteImport } from './routes/docs/dropdown-menu'
import { Route as DocsDialogRouteImport } from './routes/docs/dialog'
import { Route as DocsConfettiRouteImport } from './routes/docs/confetti'
import { Route as DocsCheckboxRouteImport } from './routes/docs/checkbox'
import { Route as DocsCardRouteImport } from './routes/docs/card'
import { Route as DocsButtonRouteImport } from './routes/docs/button'
import { Route as DocsBreadcrumbRouteImport } from './routes/docs/breadcrumb'
import { Route as DocsBadgeRouteImport } from './routes/docs/badge'
import { Route as DocsAvatarRouteImport } from './routes/docs/avatar'
import { Route as DocsAlertRouteImport } from './routes/docs/alert'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTooltipRoute = DocsTooltipRouteImport.update({
  id: '/tooltip',
  path: '/tooltip',
  getParentRoute: () => DocsRoute,
} as any)
const DocsToastRoute = DocsToastRouteImport.update({
  id: '/toast',
  path: '/toast',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTextareaRoute = DocsTextareaRouteImport.update({
  id: '/textarea',
  path: '/textarea',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTabsRoute = DocsTabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTableRoute = DocsTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSwitchRoute = DocsSwitchRouteImport.update({
  id: '/switch',
  path: '/switch',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSpinnerRoute = DocsSpinnerRouteImport.update({
  id: '/spinner',
  path: '/spinner',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSliderRoute = DocsSliderRouteImport.update({
  id: '/slider',
  path: '/slider',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSelectRoute = DocsSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => DocsRoute,
} as any)
const DocsRadioRoute = DocsRadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProgressRoute = DocsProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPhilosophyRoute = DocsPhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNavMenuRoute = DocsNavMenuRouteImport.update({
  id: '/nav-menu',
  path: '/nav-menu',
  getParentRoute: () => DocsRoute,
} as any)
const DocsLabelRoute = DocsLabelRouteImport.update({
  id: '/label',
  path: '/label',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInputRoute = DocsInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => DocsRoute,
} as any)
const DocsHidamariTextRoute = DocsHidamariTextRouteImport.update({
  id: '/hidamari-text',
  path: '/hidamari-text',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDropdownMenuRoute = DocsDropdownMenuRouteImport.update({
  id: '/dropdown-menu',
  path: '/dropdown-menu',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDialogRoute = DocsDialogRouteImport.update({
  id: '/dialog',
  path: '/dialog',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConfettiRoute = DocsConfettiRouteImport.update({
  id: '/confetti',
  path: '/confetti',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCheckboxRoute = DocsCheckboxRouteImport.update({
  id: '/checkbox',
  path: '/checkbox',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCardRoute = DocsCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => DocsRoute,
} as any)
const DocsButtonRoute = DocsButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBreadcrumbRoute = DocsBreadcrumbRouteImport.update({
  id: '/breadcrumb',
  path: '/breadcrumb',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBadgeRoute = DocsBadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAvatarRoute = DocsAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAlertRoute = DocsAlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/alert': typeof DocsAlertRoute
  '/docs/avatar': typeof DocsAvatarRoute
  '/docs/badge': typeof DocsBadgeRoute
  '/docs/breadcrumb': typeof DocsBreadcrumbRoute
  '/docs/button': typeof DocsButtonRoute
  '/docs/card': typeof DocsCardRoute
  '/docs/checkbox': typeof DocsCheckboxRoute
  '/docs/confetti': typeof DocsConfettiRoute
  '/docs/dialog': typeof DocsDialogRoute
  '/docs/dropdown-menu': typeof DocsDropdownMenuRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/hidamari-text': typeof DocsHidamariTextRoute
  '/docs/input': typeof DocsInputRoute
  '/docs/label': typeof DocsLabelRoute
  '/docs/nav-menu': typeof DocsNavMenuRoute
  '/docs/philosophy': typeof DocsPhilosophyRoute
  '/docs/progress': typeof DocsProgressRoute
  '/docs/radio': typeof DocsRadioRoute
  '/docs/select': typeof DocsSelectRoute
  '/docs/slider': typeof DocsSliderRoute
  '/docs/spinner': typeof DocsSpinnerRoute
  '/docs/switch': typeof DocsSwitchRoute
  '/docs/table': typeof DocsTableRoute
  '/docs/tabs': typeof DocsTabsRoute
  '/docs/textarea': typeof DocsTextareaRoute
  '/docs/toast': typeof DocsToastRoute
  '/docs/tooltip': typeof DocsTooltipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/alert': typeof DocsAlertRoute
  '/docs/avatar': typeof DocsAvatarRoute
  '/docs/badge': typeof DocsBadgeRoute
  '/docs/breadcrumb': typeof DocsBreadcrumbRoute
  '/docs/button': typeof DocsButtonRoute
  '/docs/card': typeof DocsCardRoute
  '/docs/checkbox': typeof DocsCheckboxRoute
  '/docs/confetti': typeof DocsConfettiRoute
  '/docs/dialog': typeof DocsDialogRoute
  '/docs/dropdown-menu': typeof DocsDropdownMenuRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/hidamari-text': typeof DocsHidamariTextRoute
  '/docs/input': typeof DocsInputRoute
  '/docs/label': typeof DocsLabelRoute
  '/docs/nav-menu': typeof DocsNavMenuRoute
  '/docs/philosophy': typeof DocsPhilosophyRoute
  '/docs/progress': typeof DocsProgressRoute
  '/docs/radio': typeof DocsRadioRoute
  '/docs/select': typeof DocsSelectRoute
  '/docs/slider': typeof DocsSliderRoute
  '/docs/spinner': typeof DocsSpinnerRoute
  '/docs/switch': typeof DocsSwitchRoute
  '/docs/table': typeof DocsTableRoute
  '/docs/tabs': typeof DocsTabsRoute
  '/docs/textarea': typeof DocsTextareaRoute
  '/docs/toast': typeof DocsToastRoute
  '/docs/tooltip': typeof DocsTooltipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/alert': typeof DocsAlertRoute
  '/docs/avatar': typeof DocsAvatarRoute
  '/docs/badge': typeof DocsBadgeRoute
  '/docs/breadcrumb': typeof DocsBreadcrumbRoute
  '/docs/button': typeof DocsButtonRoute
  '/docs/card': typeof DocsCardRoute
  '/docs/checkbox': typeof DocsCheckboxRoute
  '/docs/confetti': typeof DocsConfettiRoute
  '/docs/dialog': typeof DocsDialogRoute
  '/docs/dropdown-menu': typeof DocsDropdownMenuRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/hidamari-text': typeof DocsHidamariTextRoute
  '/docs/input': typeof DocsInputRoute
  '/docs/label': typeof DocsLabelRoute
  '/docs/nav-menu': typeof DocsNavMenuRoute
  '/docs/philosophy': typeof DocsPhilosophyRoute
  '/docs/progress': typeof DocsProgressRoute
  '/docs/radio': typeof DocsRadioRoute
  '/docs/select': typeof DocsSelectRoute
  '/docs/slider': typeof DocsSliderRoute
  '/docs/spinner': typeof DocsSpinnerRoute
  '/docs/switch': typeof DocsSwitchRoute
  '/docs/table': typeof DocsTableRoute
  '/docs/tabs': typeof DocsTabsRoute
  '/docs/textarea': typeof DocsTextareaRoute
  '/docs/toast': typeof DocsToastRoute
  '/docs/tooltip': typeof DocsTooltipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/alert'
    | '/docs/avatar'
    | '/docs/badge'
    | '/docs/breadcrumb'
    | '/docs/button'
    | '/docs/card'
    | '/docs/checkbox'
    | '/docs/confetti'
    | '/docs/dialog'
    | '/docs/dropdown-menu'
    | '/docs/getting-started'
    | '/docs/hidamari-text'
    | '/docs/input'
    | '/docs/label'
    | '/docs/nav-menu'
    | '/docs/philosophy'
    | '/docs/progress'
    | '/docs/radio'
    | '/docs/select'
    | '/docs/slider'
    | '/docs/spinner'
    | '/docs/switch'
    | '/docs/table'
    | '/docs/tabs'
    | '/docs/textarea'
    | '/docs/toast'
    | '/docs/tooltip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/alert'
    | '/docs/avatar'
    | '/docs/badge'
    | '/docs/breadcrumb'
    | '/docs/button'
    | '/docs/card'
    | '/docs/checkbox'
    | '/docs/confetti'
    | '/docs/dialog'
    | '/docs/dropdown-menu'
    | '/docs/getting-started'
    | '/docs/hidamari-text'
    | '/docs/input'
    | '/docs/label'
    | '/docs/nav-menu'
    | '/docs/philosophy'
    | '/docs/progress'
    | '/docs/radio'
    | '/docs/select'
    | '/docs/slider'
    | '/docs/spinner'
    | '/docs/switch'
    | '/docs/table'
    | '/docs/tabs'
    | '/docs/textarea'
    | '/docs/toast'
    | '/docs/tooltip'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/alert'
    | '/docs/avatar'
    | '/docs/badge'
    | '/docs/breadcrumb'
    | '/docs/button'
    | '/docs/card'
    | '/docs/checkbox'
    | '/docs/confetti'
    | '/docs/dialog'
    | '/docs/dropdown-menu'
    | '/docs/getting-started'
    | '/docs/hidamari-text'
    | '/docs/input'
    | '/docs/label'
    | '/docs/nav-menu'
    | '/docs/philosophy'
    | '/docs/progress'
    | '/docs/radio'
    | '/docs/select'
    | '/docs/slider'
    | '/docs/spinner'
    | '/docs/switch'
    | '/docs/table'
    | '/docs/tabs'
    | '/docs/textarea'
    | '/docs/toast'
    | '/docs/tooltip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/tooltip': {
      id: '/docs/tooltip'
      path: '/tooltip'
      fullPath: '/docs/tooltip'
      preLoaderRoute: typeof DocsTooltipRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/toast': {
      id: '/docs/toast'
      path: '/toast'
      fullPath: '/docs/toast'
      preLoaderRoute: typeof DocsToastRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/textarea': {
      id: '/docs/textarea'
      path: '/textarea'
      fullPath: '/docs/textarea'
      preLoaderRoute: typeof DocsTextareaRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tabs': {
      id: '/docs/tabs'
      path: '/tabs'
      fullPath: '/docs/tabs'
      preLoaderRoute: typeof DocsTabsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/table': {
      id: '/docs/table'
      path: '/table'
      fullPath: '/docs/table'
      preLoaderRoute: typeof DocsTableRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/switch': {
      id: '/docs/switch'
      path: '/switch'
      fullPath: '/docs/switch'
      preLoaderRoute: typeof DocsSwitchRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/spinner': {
      id: '/docs/spinner'
      path: '/spinner'
      fullPath: '/docs/spinner'
      preLoaderRoute: typeof DocsSpinnerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/slider': {
      id: '/docs/slider'
      path: '/slider'
      fullPath: '/docs/slider'
      preLoaderRoute: typeof DocsSliderRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/select': {
      id: '/docs/select'
      path: '/select'
      fullPath: '/docs/select'
      preLoaderRoute: typeof DocsSelectRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/radio': {
      id: '/docs/radio'
      path: '/radio'
      fullPath: '/docs/radio'
      preLoaderRoute: typeof DocsRadioRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/progress': {
      id: '/docs/progress'
      path: '/progress'
      fullPath: '/docs/progress'
      preLoaderRoute: typeof DocsProgressRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/philosophy': {
      id: '/docs/philosophy'
      path: '/philosophy'
      fullPath: '/docs/philosophy'
      preLoaderRoute: typeof DocsPhilosophyRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/nav-menu': {
      id: '/docs/nav-menu'
      path: '/nav-menu'
      fullPath: '/docs/nav-menu'
      preLoaderRoute: typeof DocsNavMenuRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/label': {
      id: '/docs/label'
      path: '/label'
      fullPath: '/docs/label'
      preLoaderRoute: typeof DocsLabelRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/input': {
      id: '/docs/input'
      path: '/input'
      fullPath: '/docs/input'
      preLoaderRoute: typeof DocsInputRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/hidamari-text': {
      id: '/docs/hidamari-text'
      path: '/hidamari-text'
      fullPath: '/docs/hidamari-text'
      preLoaderRoute: typeof DocsHidamariTextRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/dropdown-menu': {
      id: '/docs/dropdown-menu'
      path: '/dropdown-menu'
      fullPath: '/docs/dropdown-menu'
      preLoaderRoute: typeof DocsDropdownMenuRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/dialog': {
      id: '/docs/dialog'
      path: '/dialog'
      fullPath: '/docs/dialog'
      preLoaderRoute: typeof DocsDialogRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/confetti': {
      id: '/docs/confetti'
      path: '/confetti'
      fullPath: '/docs/confetti'
      preLoaderRoute: typeof DocsConfettiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/checkbox': {
      id: '/docs/checkbox'
      path: '/checkbox'
      fullPath: '/docs/checkbox'
      preLoaderRoute: typeof DocsCheckboxRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/card': {
      id: '/docs/card'
      path: '/card'
      fullPath: '/docs/card'
      preLoaderRoute: typeof DocsCardRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/button': {
      id: '/docs/button'
      path: '/button'
      fullPath: '/docs/button'
      preLoaderRoute: typeof DocsButtonRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/breadcrumb': {
      id: '/docs/breadcrumb'
      path: '/breadcrumb'
      fullPath: '/docs/breadcrumb'
      preLoaderRoute: typeof DocsBreadcrumbRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/badge': {
      id: '/docs/badge'
      path: '/badge'
      fullPath: '/docs/badge'
      preLoaderRoute: typeof DocsBadgeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/avatar': {
      id: '/docs/avatar'
      path: '/avatar'
      fullPath: '/docs/avatar'
      preLoaderRoute: typeof DocsAvatarRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/alert': {
      id: '/docs/alert'
      path: '/alert'
      fullPath: '/docs/alert'
      preLoaderRoute: typeof DocsAlertRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsAlertRoute: typeof DocsAlertRoute
  DocsAvatarRoute: typeof DocsAvatarRoute
  DocsBadgeRoute: typeof DocsBadgeRoute
  DocsBreadcrumbRoute: typeof DocsBreadcrumbRoute
  DocsButtonRoute: typeof DocsButtonRoute
  DocsCardRoute: typeof DocsCardRoute
  DocsCheckboxRoute: typeof DocsCheckboxRoute
  DocsConfettiRoute: typeof DocsConfettiRoute
  DocsDialogRoute: typeof DocsDialogRoute
  DocsDropdownMenuRoute: typeof DocsDropdownMenuRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsHidamariTextRoute: typeof DocsHidamariTextRoute
  DocsInputRoute: typeof DocsInputRoute
  DocsLabelRoute: typeof DocsLabelRoute
  DocsNavMenuRoute: typeof DocsNavMenuRoute
  DocsPhilosophyRoute: typeof DocsPhilosophyRoute
  DocsProgressRoute: typeof DocsProgressRoute
  DocsRadioRoute: typeof DocsRadioRoute
  DocsSelectRoute: typeof DocsSelectRoute
  DocsSliderRoute: typeof DocsSliderRoute
  DocsSpinnerRoute: typeof DocsSpinnerRoute
  DocsSwitchRoute: typeof DocsSwitchRoute
  DocsTableRoute: typeof DocsTableRoute
  DocsTabsRoute: typeof DocsTabsRoute
  DocsTextareaRoute: typeof DocsTextareaRoute
  DocsToastRoute: typeof DocsToastRoute
  DocsTooltipRoute: typeof DocsTooltipRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAlertRoute: DocsAlertRoute,
  DocsAvatarRoute: DocsAvatarRoute,
  DocsBadgeRoute: DocsBadgeRoute,
  DocsBreadcrumbRoute: DocsBreadcrumbRoute,
  DocsButtonRoute: DocsButtonRoute,
  DocsCardRoute: DocsCardRoute,
  DocsCheckboxRoute: DocsCheckboxRoute,
  DocsConfettiRoute: DocsConfettiRoute,
  DocsDialogRoute: DocsDialogRoute,
  DocsDropdownMenuRoute: DocsDropdownMenuRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsHidamariTextRoute: DocsHidamariTextRoute,
  DocsInputRoute: DocsInputRoute,
  DocsLabelRoute: DocsLabelRoute,
  DocsNavMenuRoute: DocsNavMenuRoute,
  DocsPhilosophyRoute: DocsPhilosophyRoute,
  DocsProgressRoute: DocsProgressRoute,
  DocsRadioRoute: DocsRadioRoute,
  DocsSelectRoute: DocsSelectRoute,
  DocsSliderRoute: DocsSliderRoute,
  DocsSpinnerRoute: DocsSpinnerRoute,
  DocsSwitchRoute: DocsSwitchRoute,
  DocsTableRoute: DocsTableRoute,
  DocsTabsRoute: DocsTabsRoute,
  DocsTextareaRoute: DocsTextareaRoute,
  DocsToastRoute: DocsToastRoute,
  DocsTooltipRoute: DocsTooltipRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
